after-login-command = []
after-startup-command = []
start-at-login = true

enable-normalization-flatten-containers = true
enable-normalization-opposite-orientation-for-nested-containers = true

accordion-padding = 30

default-root-container-layout = 'tiles'

default-root-container-orientation = 'auto'

key-mapping.preset = 'qwerty'

on-focused-monitor-changed = ['move-mouse monitor-lazy-center']
on-focus-changed = "move-mouse window-lazy-center"

[gaps]
inner.horizontal = 12
inner.vertical = 12
outer.left = 12
outer.bottom = 12
outer.top = 60
outer.right = 12

[mode.main.binding]

alt-slash = 'layout tiles horizontal vertical'
alt-comma = 'layout accordion horizontal vertical'

alt-h = 'focus left'
alt-j = 'focus down'
alt-k = 'focus up'
alt-l = 'focus right'

alt-shift-h = 'move left'
alt-shift-j = 'move down'
alt-shift-k = 'move up'
alt-shift-l = 'move right'

alt-c = 'workspace Comm' 
alt-m = 'workspace Music' 
alt-n = 'workspace Notes'
alt-p = 'workspace Personal'
alt-w = 'workspace Work' 
alt-s = 'workspace Study' 
alt-r = 'workspace Rest' 

alt-shift-c = 'move-node-to-workspace Comm'
alt-shift-m = 'move-node-to-workspace Music'
alt-shift-n = 'move-node-to-workspace Notes'
alt-shift-p = 'move-node-to-workspace Personal'
alt-shift-w = 'move-node-to-workspace Work'
alt-shift-s = 'move-node-to-workspace Study'
alt-shift-r = 'move-node-to-workspace Rest'

alt-shift-f = 'fullscreen'

alt-tab = 'workspace-back-and-forth'
alt-shift-tab = 'move-workspace-to-monitor --wrap-around next'

alt-shift-semicolon = 'mode service'

alt-shift-o = 'mode resize'

[mode.resize.binding]
h = 'resize width -50'
j = 'resize height +50'
k = 'resize height -50'
l = 'resize width +50'
b = 'balance-sizes'

minus = 'resize smart -50'
equal = 'resize smart +50'

enter = 'mode main'
esc = 'mode main'

[mode.service.binding]
esc = ['reload-config', 'mode main']
r = ['flatten-workspace-tree', 'mode main'] 
f = [
  'layout floating tiling',
  'mode main',
] 
backspace = ['close-all-windows-but-current', 'mode main']

alt-shift-h = ['join-with left', 'mode main']
alt-shift-j = ['join-with down', 'mode main']
alt-shift-k = ['join-with up', 'mode main']
alt-shift-l = ['join-with right', 'mode main']

[workspace-to-monitor-force-assignment]
W = 1
S = 1
P = 1
C = 2
M = 2
N = 1 
R = 2
